### ISSUE TITLE
Move Donate button to below install

### ISSUE THREAD

**Issue by lainsce** [tau-OS/catalogue#4]
### Problem

Donate button is on a not visible place

### Proposal

Should be on a visible place

### Prior Implementations (Optional)

https://beta.flathub.org/apps/details/com.belmoussaoui.Obfuscate

See the donate button here.

**Comment by lainsce** [comment]
Due to changes in design, both buttons would be one to the side of the other, per tauOS HIG.

**Comment by lleyton** [comment]
I agree, although I believe we should hide it in the case that it's a paid app.

**Comment by lainsce** [comment]
Fixed
